### PR TITLE
Attempt to describe extensively an API used in Heracles.ts

### PR DESCRIPTION
**Pull request by alien-mcl**
Please find the attached use case focused on extensive API documentation of the API used in the Heracles.ts implementation that is related to events.

Please feel free to elaborate as it came out that the task was not easy.

---
This change is [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)

### CODE REVIEW

**Comment by alien-mcl** [comment]
@lanthaler, @tpluscode, @elf-pavlik, any update on this?

**Comment by lanthaler** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 18 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHOjvS7YhwKTbeX2gc:-LBHOjvS7YhwKTbeX2gd:b-b6vkre) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L18)):*
> ```Markdown
>   - name
>   - description
>   - base classes
> ```

Do you mean parent/super-classes?

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 40 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHP4uv4JwardklmAHo:-LBHP4uw0sr-QDAw4khs:b-pbd6rp) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L40)):*
> ```Markdown
> @base <http://temp.uri/api> .
> 
> <?apiDocumentation> a hydra:ApiDocumentation;
> ```

I'd think making this `<>` instead of `<?apiDocumentation>` would simplify things.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 48 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPFNZ4g8XnxpvBz9L:-LBHPFN_6-TfqTMVc7fp:bz7i1gj) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L48)):*
> ```Markdown
> schema:Event a hydra:Class ;
>     hydra:supportedOperation doc:get-events-operation ,
>         doc:new-event-operation ,
> ```

I'd get rid of the `doc:` prefix and instead use relative IRIs directly, in this case <#new-even-operation>. That makes it clear that the description can be found further down in the same doc

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 84 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPsPE5ZdMOFshH-k2:-LBHPsPE5ZdMOFshH-k3:bxmop9j) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L84)):*
> ```Markdown
> # Below are operations related to schema:Event supported class.
> # Unfortunately, it is not possible to link them directly to the supported class
> # as the hydra:Operation does not allow to define the URL to be invoked.
> ```

You could reference the issue in which we are working on that here

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 89 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPfvO63lDYJ_Balsw:-LBHPfvO63lDYJ_Balsx:b-27yugf) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L89)):*
> ```Markdown
> # The link below does not allow to describe the fact returned payload is a collection of schema:Event,
> # thus the only hint for the client to connect it with that class is comparing supported operations 
> # defined in this link and the class itsefl.
> ```

itsefl --> itself

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 110 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQ8pE-mjaNEKrmSAU:-LBHQ8pE-mjaNEKrmSAV:bbm154a) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L110)):*
> ```Markdown
> doc:update-event a hydra:TemplatedLink ;
>     hydra:title "Updates an event." ;
>     hydra:template "http://temp.uri/api/events/{id}"^^hydra:Rfc6570Template ;
> ```

`hydra:template` and `hydra:mapping` can't be used on the definition of a TemplatedLink. They need to be set when such a link is instantiated.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 119 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQaX47tRg58Q2OLvi:-LBHQaX47tRg58Q2OLvj:bj4rnpc) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L119)):*
> ```Markdown
>     ] .
> 
> # Link below cannot be directly connected with schema:Event class as it does not mention it.
> ```

What do you mean by this? You declared there to be a supported operation of schema:Event that allows deleting the event. In general, I don't understand what you use these TemplatedLinks here for!?

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 18 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHOjvS7YhwKTbeX2gc:-LCUpJLM45IObr3DADKl:bbzlskv) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L18)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Do you mean parent/super-classes?
</blockquote></details>

Yes, should I retype it?

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 110 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQ8pE-mjaNEKrmSAU:-LCUpew62vEVddfrffv0:b-d0w3hj) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L110)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

`hydra:template` and `hydra:mapping` can't be used on the definition of a TemplatedLink. They need to be set when such a link is instantiated.
</blockquote></details>

OK, but are there any alternatives? How to tell on API documentation level that there is an IRI template link?

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by lanthaler** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 18 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHOjvS7YhwKTbeX2gc:-LDWSQeM77v6PAiTmfsZ:buz1jq0) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L18)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Yes, should I retype it?
</blockquote></details>

Yeah, I think it would clarify it

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 110 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQ8pE-mjaNEKrmSAU:-LDWSdaL1xGCkEG-jJnx:bu36vhc) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L110)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

OK, but are there any alternatives? How to tell on API documentation level that there is an IRI template link?
</blockquote></details>

That's currently not possible

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 18 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHOjvS7YhwKTbeX2gc:-LDXji3yByAj8p9y8J0N:b-896fix) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L18)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

Yeah, I think it would clarify it
</blockquote></details>

Done.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 40 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHP4uv4JwardklmAHo:-LDXjnbR0-NDQ4Lt8Y-c:b-xjf0qk) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L40)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I'd think making this `<>` instead of `<?apiDocumentation>` would simplify things.
</blockquote></details>

But `<>` is an API's entry point, which is not it's API documentation.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 48 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPFNZ4g8XnxpvBz9L:-LDXjysE-i18IDWmjcrP:bfd44dn) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L48)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I'd get rid of the `doc:` prefix and instead use relative IRIs directly, in this case <#new-even-operation>. That makes it clear that the description can be found further down in the same doc
</blockquote></details>

As previously - `@base` points to the API entry point, `doc:` prefix points to the API documentation, which are separate beings. I feel some IRI re-factorization is necessary here - any suggestions?

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 84 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPsPE5ZdMOFshH-k2:-LDXkjbQDwH5z9pfNtBT:b-896fix) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L84)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

You could reference the issue in which we are working on that here
</blockquote></details>

Done.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 89 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPfvO63lDYJ_Balsw:-LDXklv85yeTMpZsMiTx:b-896fix) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L89)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

itsefl --> itself
</blockquote></details>

Done.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 110 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQ8pE-mjaNEKrmSAU:-LDXmEeH7k8jm_u_HnNv:b-cceowl) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L110)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

That's currently not possible
</blockquote></details>

I've added an issue to address this.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 119 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQaX47tRg58Q2OLvi:-LDXmNmV7m5GnZ0Ob1py:b-tlwe14) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L119)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

What do you mean by this? You declared there to be a supported operation of schema:Event that allows deleting the event. In general, I don't understand what you use these TemplatedLinks here for!?
</blockquote></details>

I'd like to give a client a hint, that it can use `GET`, `PUT` and `DELETE` methods on a very specific instances that can be addressed with an IRI template.

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by lanthaler** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 40 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHP4uv4JwardklmAHo:-LE5L2B_48kpCwrW_9rV:b-ufsl23) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L40)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

But `<>` is an API's entry point, which is not it's API documentation.
</blockquote></details>

It's a relative URL so it depends on where it is hosted (resp. what `@base` says). The main I'd like to avoid is the use of a query param. If you don't like `<>` please make it `</apiDocumentation>` or something similar. I have seen people being confused about this in the past where they thought they would need to return the API docs if something like `?apiDocumentation` is appended to any of their URLs.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 48 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPFNZ4g8XnxpvBz9L:-LE5LmXL-tp3Zw9goFqW:bheh3r0) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L48)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

As previously - `@base` points to the API entry point, `doc:` prefix points to the API documentation, which are separate beings. I feel some IRI re-factorization is necessary here - any suggestions?
</blockquote></details>

I typically prefer to use relative URLs (mostly fragments) for everything that can be found in the same document. Let's just get rid of `@base` and use full, absolute URLs (or path-absolute URLs) for everything else

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 119 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQaX47tRg58Q2OLvi:-LE5Mme-2q1zXV89ntR4:b9h2nkq) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L119)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

I'd like to give a client a hint, that it can use `GET`, `PUT` and `DELETE` methods on a very specific instances that can be addressed with an IRI template.
</blockquote></details>

I think what you want in that case is a concrete IRI template with those operations attached to it. You don't need a TemplatedLink property for that. That being said, a client wouldn't necessarily use this as of now as there's no way to connect it to a ApiDocumentation (but it would be straightforward to add)

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @lanthaler)

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 40 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHP4uv4JwardklmAHo:-LEpY2RR4mYVfnDc3qX-:b-896fix) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L40)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

It's a relative URL so it depends on where it is hosted (resp. what `@base` says). The main I'd like to avoid is the use of a query param. If you don't like `<>` please make it `</apiDocumentation>` or something similar. I have seen people being confused about this in the past where they thought they would need to return the API docs if something like `?apiDocumentation` is appended to any of their URLs.
</blockquote></details>

Done.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 48 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPFNZ4g8XnxpvBz9L:-LEpWl0F7U_l5dJ4zMcK:b-896fix) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L48)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I typically prefer to use relative URLs (mostly fragments) for everything that can be found in the same document. Let's just get rid of `@base` and use full, absolute URLs (or path-absolute URLs) for everything else
</blockquote></details>

Done.

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 119 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHQaX47tRg58Q2OLvi:-LEpXwo47ecXBQuHGqva:b-896fix) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L119)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

I think what you want in that case is a concrete IRI template with those operations attached to it. You don't need a TemplatedLink property for that. That being said, a client wouldn't necessarily use this as of now as there's no way to connect it to a ApiDocumentation (but it would be straightforward to add)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by lanthaler** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @lanthaler)

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 48 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPFNZ4g8XnxpvBz9L:-LF1BxdhENQbKcbcuI05:b3s7no1) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L48)):*
<details><summary><i>Previously, alien-mcl (Karol Szczepański) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You forgot to get rid of `@base`

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164#-:-LF1CEpQCGWqDv1-vZqM:bnfp4nl)*

**Comment by alien-mcl** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @lanthaler)

---

*[drafts/use-cases/2.3.complete-api-documentation.md, line 48 at r1](https://reviewable.io/reviews/hydracg/specifications/164#-LBHPFNZ4g8XnxpvBz9L:-LFTW0Hz-iro-QTHyx4A:bb6un1j) ([raw file](https://github.com/hydracg/specifications/blob/c46a6c87fb68dce55656d41ee200d38e2cbf051d/drafts/use-cases/2.3.complete-api-documentation.md#L48)):*
<details><summary><i>Previously, lanthaler (Markus Lanthaler) wrote…</i></summary><blockquote>

You forgot to get rid of `@base`
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by lanthaler** [comment]
Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/hydracg/specifications/164)*

**Comment by hyprdia** [comment]
I know this has been a while since this was merged, but I start to design a quite complex API using Hydra and I have an issue with (not the example but the `hydra:SupportedProperty` ): 

```turtle 
    a hydra:SupportedProperty ;
    hydra:propety vocab:id ;
    hydra:required "true"^^xsd:boolean ;
    hydra:writable "true"^^xsd:boolean ;
    hydra:readable "true"^^xsd:boolean ] ;
```

since this is defined in the documentation, it seems to assume that the `required`, `writable` and `readable` values will be valid in all situations. In my API, a particular `supportedClass`, and I have many examples of this, may sometimes support `writable`(`readable`) but sometimes not, it could depend on many factors such as: the context in which the `supportedClass` instance is found, its state, the permissions of the user/client seeing the instance.

My questions: can the API documentation not provide this information when it cannot be provided (are they required properties)? Would the API still be Hydra compatible in such case?

**Comment by hyprdia** [comment]
Just saw the `maxCardinality` in the last spec version. No need to answer, thanks.

**Pull request merged**
