### PR TITLE
Implement “remove predefined operations”

### PR DESCRIPTION
**Pull request by RubenVerborgh**
This pull request **partially** addresses #11 by removing the predefined operations from the vocabulary.
However, I need some input to finalize this.
1. Should `hydra:Operation` be removed/replaced? And if so, what about `hydra:supportedOperation`, `hydra:operation`, `hydra:method`, `hydra:expects`, `hydra:returns`?
2. In the specification document, should we remove explanations about `CreateResourceOperation`, `ReplaceResourceOperation` and `DeleteResourceOperation`? Or should we, as suggested in #11, replace them by Schema.org explanations? The latter, however, need not necessarily be part of the spec.

As a temporary resolution for the second point, I propose to remove. We can always add explanations later (but perhaps already create an issue for that then).

### CODE REVIEW

**Comment by luchsamapparat** [comment]
Hi,

is there any roadmap on when to expect this Change? I'm currently exploring Hydra and I'm unsure how to proceed

**Comment by tpluscode** [comment]
@RubenVerborgh Why do you propose removing `hydra:Operation` and others? Following [this comment ](https://github.com/HydraCG/Specifications/issues/2#issuecomment-269014538) in #2 I think that operations do have their place describing HTTP protocol and actions being used in API-specific terms.

For second point, I think it may be good to actually add schema actions as illustrations of suggested usage.

**Comment by RubenVerborgh** [comment]
@tpluscode I think the question should be the other way round: why do we need them? As announced on the mailing list, I'd like to take a step back and start with a clean slate from the lessons we learned. It might well be that we need something like operation.

(Sketching a proposed architectural diagram as we speak, I expect to send this out today.)

**Comment by RubenVerborgh** [comment]
[Architectural diagram (draft)](https://github.com/RubenVerborgh/Hydra-Architecture-Diagram/)

**Comment by lanthaler** [comment]
I'm fine with removing CreateResourceOperation, ReplaceResourceOperation, and DeleteResourceOperation. I agree with @tpluscode that we will likely need `hydra:Operation` etc. Should we proceed with merging this PR and discuss the rest separately? 

Unless I hear objections, I'll merge this PR on the weekend (we previously agreed to delete them in #11).

**Comment by asbjornu** [comment]
👍  for deleting the concrete operations while keeping the generic `hydra:Operation`.

**Pull request merged**
