### PR TITLE
Reference the automatically created diagram

### PR DESCRIPTION
**Pull request by lanthaler**

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
The link is broken; I suspect Travis integration has not been enabled (https://github.com/HydraCG/Specifications/pull/128#issuecomment-311126689).

**Comment by lanthaler** [comment]
No, it seems the Travis configuration is wrong: https://travis-ci.org/HydraCG/Specifications/jobs/252151680

**Comment by RubenVerborgh** [comment]
I've force-pushed a new fix on this branch; the script only runs in the master branch though.

**Comment by lanthaler** [comment]
Had to apply a few fixes. It works now

**Pull request merged**
